version: '3'

services:

  web1:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code1
    ports:
      - "8000:8000"
    depends_on:
    - postgresql
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.3
    container_name: elasticsearch613
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.zen.minimum_master_nodes=1
      - discovery.type=single-node
#      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
#      - xpack.license.self_generated.type=trial
#      - xpack.security.enabled=true
#      - xpack.security.http.ssl.enabled=true
#      - xpack.security.transport.ssl.enabled=true
#      - xpack.security.transport.ssl.verification_mode=certificate
#      - xpack.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
#      - xpack.ssl.certificate=$CERTS_DIR/es01/es01.crt
#      - xpack.ssl.key=$CERTS_DIR/es01/es01.key
    volumes:
      - esdata:/usr/share/elasticsearch613/data
#      - ./certs:$CERTS_DIR
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK

  postgresql:
    container_name: postgresql
    image: "postgres:10.0"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ava100
      PGDATA: / tmp


  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.3
    container_name: kibana1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch613:9200
      - ELASTICSEARCH_PORT=9200
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
  headPlugin:
    image: mobz/elasticsearch-head:5
    container_name: head1
    ports:
      - 9100:9100

volumes:
  {"esdata": {"driver": "local"} , pgdata: {"driver": "local"}}



# install Docker & Docker compose :
# sudo apt install docker.io
# sudo pip uninstall docker docker-compose
# sudo apt-get update
# sudo apt-get upgrade
# sudo apt-get install docker docker-compose
# https://rasooll.com/how-to-use-docker-in-iran/