# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 08:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('blog', '0003_auto_20190504_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnailImage',
            field=filer.fields.image.FilerImageField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='blog_thumb_image', to=settings.FILER_IMAGE_MODEL),
            preserve_default=False,
        ),
    ]
