# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 08:06
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loc_category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='Doctors.Loc_Category'),
        ),
        migrations.AlterField(
            model_name='spec_category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='Doctors.Spec_Category'),
        ),
    ]
