# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0002_auto_20190504_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorspost',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doctorspost',
            name='site',
            field=models.URLField(blank=True),
        ),
    ]
